### ISSUE TITLE
[tts] speaker fails to playback tts

### ISSUE THREAD

**Issue by Nokius** [Limych/media_player.linkplay#26]
## Version of the custom_component

VERSOIN = '1.1.6' plus #25 patch

## Configuration

```yaml

media_player:
  - platform: linkplay
    host: 192.168.2.12
    device_name: livingroom
  - platform: linkplay
    host: 192.168.2.13
    device_name: office

tts:
  - plattform: google_translate
    language: de

```

## Describe the bug
With Version 0.110.0 when the enaming of the MediaPlayerDevice entitiy is started. That the playback of tts is failing on my linkplay speakers. I tested it with my other setup and it works with other speakers still well. Anyone else having the problem or may knows a fix? Yes I patched the component as decribed in #25.

Steps to reprouce:

open speaker in the HA ui
type in text for tts
play press
you will hear nothing (ui grays out the speaker for a moment)

## Debug log

```text

nohing to see in the logs :(

![Bildschirmfoto 2020-09-05 um 14 11 40](https://user-images.githubusercontent.com/879178/92304849-15dfd900-ef82-11ea-8dce-52942a3d1c7d.png)


```
